//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Bank> tbl_Bank { get; set; }
        public virtual DbSet<tbl_Bank_Master> tbl_Bank_Master { get; set; }
        public virtual DbSet<tbl_Base_Unit> tbl_Base_Unit { get; set; }
        public virtual DbSet<tbl_Brand_Master> tbl_Brand_Master { get; set; }
        public virtual DbSet<tbl_BusinessPartner_Master> tbl_BusinessPartner_Master { get; set; }
        public virtual DbSet<tbl_Cntp_Person> tbl_Cntp_Person { get; set; }
        public virtual DbSet<tbl_Company_Master> tbl_Company_Master { get; set; }
        public virtual DbSet<tbl_Country_Master> tbl_Country_Master { get; set; }
        public virtual DbSet<tbl_Currency_Master> tbl_Currency_Master { get; set; }
        public virtual DbSet<tbl_Item_Group> tbl_Item_Group { get; set; }
        public virtual DbSet<tbl_Item_Master> tbl_Item_Master { get; set; }
        public virtual DbSet<tbl_Item_Type> tbl_Item_Type { get; set; }
        public virtual DbSet<tbl_Manufacturer> tbl_Manufacturer { get; set; }
        public virtual DbSet<tbl_Payment_Mode> tbl_Payment_Mode { get; set; }
        public virtual DbSet<tbl_State_Master> tbl_State_Master { get; set; }
        public virtual DbSet<tbl_Tax> tbl_Tax { get; set; }
        public virtual DbSet<tbl_Tax_Master> tbl_Tax_Master { get; set; }
        public virtual DbSet<tbl_TransactionLog_Master> tbl_TransactionLog_Master { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
