//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int user_Id { get; set; }
        public Nullable<int> cmpny_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string user_name { get; set; }
        public string pass { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public Nullable<int> state_id { get; set; }
        public string zip_code { get; set; }
        public string desig { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
        public virtual tbl_State_Master tbl_State_Master { get; set; }
    }
}
