//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Manufacturer()
        {
            this.tbl_Brand_Master = new HashSet<tbl_Brand_Master>();
            this.tbl_Item_Master = new HashSet<tbl_Item_Master>();
        }
    
        public int manuf_Id { get; set; }
        public Nullable<int> cmpny_Id { get; set; }
        public Nullable<int> bp_Id { get; set; }
        public string manuf_name { get; set; }
        public string reference { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Brand_Master> tbl_Brand_Master { get; set; }
        public virtual tbl_BusinessPartner_Master tbl_BusinessPartner_Master { get; set; }
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Master> tbl_Item_Master { get; set; }
    }
}
