//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item_Master
    {
        public int itemmaster_Id { get; set; }
        public Nullable<int> cmpny_Id { get; set; }
        public Nullable<int> itemtype_Id { get; set; }
        public Nullable<int> bu_Id { get; set; }
        public Nullable<int> manuf_Id { get; set; }
        public Nullable<int> bp_id { get; set; }
        public string item_name { get; set; }
        public Nullable<int> std { get; set; }
        public string sup_barcode { get; set; }
        public string srch_key { get; set; }
        public Nullable<int> itemgrp_Id { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public Nullable<decimal> retail_price { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> item_cost { get; set; }
        public Nullable<decimal> inventory_val { get; set; }
        public Nullable<int> rec_level { get; set; }
        public Nullable<int> rec_qry { get; set; }
        public Nullable<int> eco_order_qty { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Base_Unit tbl_Base_Unit { get; set; }
        public virtual tbl_BusinessPartner_Master tbl_BusinessPartner_Master { get; set; }
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
        public virtual tbl_Item_Group tbl_Item_Group { get; set; }
        public virtual tbl_Manufacturer tbl_Manufacturer { get; set; }
    }
}
