//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Item_Group()
        {
            this.tbl_Item_Master = new HashSet<tbl_Item_Master>();
        }
    
        public int itemgrp_Id { get; set; }
        public Nullable<int> cmpny_Id { get; set; }
        public Nullable<int> taxmaster_Id { get; set; }
        public string itemgrp_name { get; set; }
        public string cess { get; set; }
        public string reference { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
        public virtual tbl_Tax_Master tbl_Tax_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Master> tbl_Item_Master { get; set; }
    }
}
