//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cntp_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Cntp_Person()
        {
            this.tbl_BusinessPartner_Master = new HashSet<tbl_BusinessPartner_Master>();
        }
    
        public int cntp_Id { get; set; }
        public string cntp_name { get; set; }
        public Nullable<int> cmpny_Id { get; set; }
        public string salution { get; set; }
        public string cntp_lastname { get; set; }
        public string cntp_displayname { get; set; }
        public Nullable<int> designation_Id { get; set; }
        public string office_phone { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public Nullable<int> state_id { get; set; }
        public string zip_code { get; set; }
        public string map { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
        public string err_msg { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessPartner_Master> tbl_BusinessPartner_Master { get; set; }
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
        public virtual tbl_State_Master tbl_State_Master { get; set; }
    }
}
