//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Company_Master()
        {
            this.tbl_Bank = new HashSet<tbl_Bank>();
            this.tbl_Bank_Master = new HashSet<tbl_Bank_Master>();
            this.tbl_Base_Unit = new HashSet<tbl_Base_Unit>();
            this.tbl_Brand_Master = new HashSet<tbl_Brand_Master>();
            this.tbl_BusinessPartner_Master = new HashSet<tbl_BusinessPartner_Master>();
            this.tbl_Cntp_Person = new HashSet<tbl_Cntp_Person>();
            this.tbl_Currency_Master = new HashSet<tbl_Currency_Master>();
            this.tbl_Item_Group = new HashSet<tbl_Item_Group>();
            this.tbl_Item_Master = new HashSet<tbl_Item_Master>();
            this.tbl_Item_Type = new HashSet<tbl_Item_Type>();
            this.tbl_Manufacturer = new HashSet<tbl_Manufacturer>();
            this.tbl_Payment_Mode = new HashSet<tbl_Payment_Mode>();
            this.tbl_State_Master = new HashSet<tbl_State_Master>();
            this.tbl_Tax_Master = new HashSet<tbl_Tax_Master>();
            this.tbl_Tax = new HashSet<tbl_Tax>();
            this.tbl_TransactionLog_Master = new HashSet<tbl_TransactionLog_Master>();
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int cmpny_Id { get; set; }
        public string cmpny_code { get; set; }
        public string cmpny_name { get; set; }
        public string display_name { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public string cin { get; set; }
        public Nullable<int> base_currency_code { get; set; }
        public string reg_phone { get; set; }
        public Nullable<int> reg_phone_status { get; set; }
        public string reg_email { get; set; }
        public Nullable<int> reg_email_status { get; set; }
        public string tin { get; set; }
        public string tan { get; set; }
        public string pan { get; set; }
        public string cst { get; set; }
        public string gst { get; set; }
        public Nullable<int> cntp_person_Id { get; set; }
        public string eu_code { get; set; }
        public string eu_name { get; set; }
        public string logo { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
        public string err_msg { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bank> tbl_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bank_Master> tbl_Bank_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Base_Unit> tbl_Base_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Brand_Master> tbl_Brand_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessPartner_Master> tbl_BusinessPartner_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cntp_Person> tbl_Cntp_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Currency_Master> tbl_Currency_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Group> tbl_Item_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Master> tbl_Item_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Type> tbl_Item_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Manufacturer> tbl_Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Payment_Mode> tbl_Payment_Mode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_State_Master> tbl_State_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tax_Master> tbl_Tax_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tax> tbl_Tax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TransactionLog_Master> tbl_TransactionLog_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
