//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Mode
    {
        public int pmode_Id { get; set; }
        public Nullable<int> cmpany_id { get; set; }
        public Nullable<int> bank_Id { get; set; }
        public string pmode_name { get; set; }
        public Nullable<int> pmode_transaction { get; set; }
        public string acc_mode { get; set; }
        public string reference { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Bank tbl_Bank { get; set; }
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
    }
}
