//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransactionLog_Master
    {
        public int translog_Id { get; set; }
        public string transaction_Id { get; set; }
        public Nullable<int> cmpny_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<int> transaction_status { get; set; }
        public Nullable<int> user_Id { get; set; }
        public string log_msg { get; set; }
    
        public virtual tbl_Company_Master tbl_Company_Master { get; set; }
    }
}
